<?xml version="1.0"?>
<robot name="ackermann_robot" xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find ackermann_simulation)/urdf/wheels.xacro"/>
	<xacro:include filename="$(find ackermann_simulation)/urdf/steering_wheels.xacro"/>
	<xacro:include filename="$(find ackermann_simulation)/urdf/lidar.xacro"/>

	<xacro:property name="M_PI_2" value="1.570796327"/>
	<xacro:property name="wheel_radius" value="0.075"/>
	<xacro:property name="wheel_height" value="0.04"/>
	<xacro:property name="wheel_mass" value="1.5"/>

	<link name="base_footprint"></link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

	<link name="base_link">
		<visual>
			<origin rpy="0 0 0" xyz="-0.785 -0.747 -${wheel_radius*2}"/>
			<geometry>
				<mesh filename="model://ackermann_model/meshes/base_link.stl" scale="0.01 0.01 0.01" />
			</geometry>
			<material name="red">
				<color rgba="0.8 0.0 0.0 1.0"/>
			</material>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="-0.035 0 0.02"/>
			<geometry>
				<box size="1 0.38 0.24"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="15.0"/>
			<origin xyz="0.0 0 0.0"/>
			<inertia ixx="2.3" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.5"/>
		</inertial>
	</link>

	<gazebo reference="base_link">
		<selfCollide>false</selfCollide>
		<material value="Gazebo/Red"/>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

	<!-- The steering wheels -->
	<xacro:steering_wheel name="front_left" parent="base_link" limit_low="-1e+16" limit_high="1e+16" >
		<origin xyz="0.308 0.175 -${wheel_radius}" rpy="0 0 0"/>
	</xacro:steering_wheel>
	<xacro:steering_wheel name="front_right" parent="base_link" limit_low="-1e+16" limit_high="1e+16" >
		<origin xyz="0.308 -0.175 -${wheel_radius}" rpy="0 0 0"/>
	</xacro:steering_wheel>

	<!-- wheels -->
	<xacro:wheel name="back_left" parent="base_link" >
		<origin xyz="-0.308 0.175 -${wheel_radius}" rpy="0 0 0"/>
	</xacro:wheel>
	<xacro:wheel name="back_right" parent="base_link" >
		<origin xyz="-0.308 -0.175 -${wheel_radius}" rpy="0 0 0"/>
	</xacro:wheel>

	<gazebo>
		<plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <remapping>~/out:=joint_states</remapping>
      </ros>
      <update_rate>30</update_rate>
      <joint_name>wheel_front_left_joint</joint_name>
      <joint_name>wheel_front_right_joint</joint_name>
      <joint_name>wheel_back_left_joint</joint_name>
      <joint_name>wheel_back_right_joint</joint_name>
      <joint_name>steering_wheel_front_left_joint</joint_name>
      <joint_name>steering_wheel_front_right_joint</joint_name>
    </plugin> 
		<plugin name="gazebo_ros_ackermann_drive" filename="libgazebo_ros_ackermann_drive.so">
      <update_rate>100.0</update_rate>
      <!-- wheels -->
      <front_left_joint>wheel_front_left_joint</front_left_joint>
      <front_right_joint>wheel_front_right_joint</front_right_joint>
      <rear_left_joint>wheel_back_left_joint</rear_left_joint>
      <rear_right_joint>wheel_back_right_joint</rear_right_joint>
      <left_steering_joint>steering_wheel_front_left_joint</left_steering_joint>
      <right_steering_joint>steering_wheel_front_right_joint</right_steering_joint>
      <!-- <steering_wheel_joint>steering_joint</steering_wheel_joint> -->
      <!-- Max absolute steer angle for tyre in radians-->
      <!-- Any cmd_vel angular z greater than this would be capped -->
      <max_steer>0.6458</max_steer>
      <!-- Max absolute steering angle of steering wheel -->
      <!-- <max_steering_angle>7.85</max_steering_angle> -->
      <!-- Max absolute linear speed in m/s -->
      <max_speed>20</max_speed>
      <!-- PID tuning -->
      <left_steering_pid_gain>1500 0 1</left_steering_pid_gain>
      <left_steering_i_range>0 0</left_steering_i_range>
      <right_steering_pid_gain>1500 0 1</right_steering_pid_gain>
      <right_steering_i_range>0 0</right_steering_i_range>
      <linear_velocity_pid_gain>1000 0 1</linear_velocity_pid_gain>
      <linear_velocity_i_range>0 0</linear_velocity_i_range>
      <!-- output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <publish_distance>true</publish_distance>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
    </plugin>
	</gazebo>

	<xacro:lidar name="lidar" parent="base_link">
		<origin xyz="-0.06 0.0 0.165" rpy="0 0 0"/>
	</xacro:lidar>

</robot>